#!/usr/bin/env python3
"""Parse the Astronaut EHR Export Format Documentation PDF.
Extracts structured info about sections, format details, and produces
entity-inventory-full.json and entity-inventory-summary.json."""

import json
import subprocess
import re

# Extract text from PDF
result = subprocess.run(
    ["pdftotext", "-layout", "../downloads/Astronaut-EHR-Export-Format-Documentation.pdf", "-"],
    capture_output=True, text=True
)
text = result.stdout

# Parse C-CDA sections from the document
ccda_sections = [
    {"name": "Allergies", "description": "Lists medication allergies, adverse reactions, idiosyncratic reactions, anaphylaxis/anaphylactoid reactions to food items, and metabolic variations or adverse reactions/allergies to other substances."},
    {"name": "Immunizations", "description": "Defines a patient's current immunization status and pertinent immunization history."},
    {"name": "Medications", "description": "Contains a patient's current medications, prescriptions and information about intended drug monitoring."},
    {"name": "Plan of Treatment", "description": "Contains data that define pending orders, interventions, encounters, services, and procedures. Limited to prospective, unfulfilled, or incomplete orders and requests."},
    {"name": "Goals", "description": "Represents patient Goals - defined outcomes or conditions to be achieved in the process of patient care."},
    {"name": "Problems", "description": "Lists and describes all relevant clinical problems. Includes diagnoses a patient has in their chart."},
    {"name": "Results (Lab)", "description": "Contains observations of results generated by laboratories, imaging procedures, and other procedures."},
    {"name": "Vitals", "description": "Contains relevant vital signs such as blood pressure, heart rate, respiratory rate, height, weight, BMI, head circumference, pulse oximetry, temperature, and body surface area."},
    {"name": "Procedures", "description": "Describes all interventional, surgical, diagnostic, or therapeutic procedures or treatments pertinent to the patient."},
    {"name": "Social History", "description": "Contains social history data that influence a patient's physical, psychological or emotional health (e.g., smoking status, pregnancy)."},
    {"name": "Encounters", "description": "Lists and describes any healthcare encounters pertinent to the patient's current health status or historical health history."},
    {"name": "Functional Status", "description": "Contains observations and assessments of a patient's physical abilities, including ADLs."},
    {"name": "Medical Equipment", "description": "Defines a patient's implanted and external health and medical devices and equipment, including DME."},
    {"name": "Assessments", "description": "Represents the clinician's conclusions and working assumptions that will guide treatment of the patient."},
]

# The CSV section
csv_section = {
    "name": "Advanced Demographics and Remaining EHI",
    "format": "CSV (name-value pairs)",
    "description": "Advanced demographics and remaining EHI bundled in proprietary CSV format. Name-value pair layout where demographic name is followed by its value. Example: 'Place of Birth, USA, Mother's Maiden Name, Annabelle, ...'",
    "example_fields": ["Place of Birth", "Mother's Maiden Name", "Spouse's Employer Name", "Date of Retirement"],
    "note": "No complete field list provided. Documentation states 'deciphering the data is fairly straightforward' and 'categories that have no data assigned to them' are excluded."
}

# Build entity inventory
entities = []

# C-CDA sections as entities (no field-level detail provided)
for section in ccda_sections:
    entities.append({
        "entity_name": f"C-CDA Section: {section['name']}",
        "format": "C-CDA XML",
        "category": "C-CDA Clinical Data",
        "description": section["description"],
        "fields": [],
        "field_count": 0,
        "fields_with_descriptions": 0,
        "fields_with_types": 0,
        "note": "No product-specific field-level documentation provided. Vendor refers to HL7's official C-CDA documentation for field details."
    })

# CSV section
entities.append({
    "entity_name": "Advanced Demographics and Remaining EHI",
    "format": "CSV (proprietary name-value pairs)",
    "category": "Demographics / Other EHI",
    "description": csv_section["description"],
    "fields": [
        {"name": f, "type": None, "description": None, "source": "example in documentation"}
        for f in csv_section["example_fields"]
    ],
    "field_count": 4,
    "fields_with_descriptions": 0,
    "fields_with_types": 0,
    "note": "Only 4 example fields shown in documentation. No complete field list provided."
})

# C-CDA header (demographics)
entities.append({
    "entity_name": "C-CDA Header (Patient Demographics)",
    "format": "C-CDA XML",
    "category": "Demographics",
    "description": "Header section contains metadata such as patient demographics, author information, document type, and timestamps. Demographic data including marital status, race, ethnicity, and religious affiliation captured here.",
    "fields": [],
    "field_count": 0,
    "fields_with_descriptions": 0,
    "fields_with_types": 0,
    "note": "No product-specific field-level documentation provided."
})

inventory = {
    "product": "Astronaut EHR",
    "source_file": "downloads/Astronaut-EHR-Export-Format-Documentation.pdf",
    "source_pages": 10,
    "extraction_notes": "No data dictionary or field-level documentation exists in the source PDF. Entities represent C-CDA sections described at summary level only, plus a proprietary CSV component with minimal detail.",
    "total_entities": len(entities),
    "total_documented_fields": sum(e["field_count"] for e in entities),
    "entities": entities
}

with open("entity-inventory-full.json", "w") as f:
    json.dump(inventory, f, indent=2)

# Summary
summary = {
    "product": "Astronaut EHR",
    "source_file": "downloads/Astronaut-EHR-Export-Format-Documentation.pdf",
    "total_entities": len(entities),
    "total_documented_fields": sum(e["field_count"] for e in entities),
    "total_fields_with_descriptions": sum(e["fields_with_descriptions"] for e in entities),
    "total_fields_with_types": sum(e["fields_with_types"] for e in entities),
    "format": "C-CDA XML + proprietary CSV",
    "has_data_dictionary": False,
    "has_sample_data": False,
    "has_schema": False,
    "ccda_section_count": 14,
    "csv_example_fields": 4,
    "categories": {
        "C-CDA Clinical Data": {
            "entity_count": 14,
            "field_count": 0,
            "note": "No field-level documentation; refers to HL7 C-CDA spec"
        },
        "Demographics / Other EHI": {
            "entity_count": 1,
            "field_count": 4,
            "note": "Only example fields from documentation"
        },
        "Demographics": {
            "entity_count": 1,
            "field_count": 0,
            "note": "C-CDA header; no field-level detail"
        }
    },
    "documentation_quality": {
        "field_level_detail": "None - no individual fields documented",
        "type_documentation": "None",
        "relationship_documentation": "None",
        "value_set_documentation": "None",
        "sample_data": "1 fictional CSV example (4 fields)",
        "machine_readable_artifacts": "None"
    }
}

with open("entity-inventory-summary.json", "w") as f:
    json.dump(summary, f, indent=2)

print(f"Entities: {len(entities)}")
print(f"Documented fields: {sum(e['field_count'] for e in entities)}")
print(f"C-CDA sections: 14")
print(f"CSV example fields: 4")
print("Saved entity-inventory-full.json and entity-inventory-summary.json")
