#!/usr/bin/env python3
"""Analyze all EHI export artifacts for Nexus EHR and produce structured inventory."""

import json
import subprocess
import os

DOWNLOADS = "/home/jmandel/hobby/ehi-export-analysis/results/nexus-clinical-llc--nexus-ehr/downloads"
OUTPUT_DIR = "/home/jmandel/hobby/ehi-export-analysis/abstraction/nexus-clinical-llc--nexus-ehr/analysis"

def get_pdf_info(path):
    """Extract metadata from a PDF."""
    result = subprocess.run(["pdfinfo", path], capture_output=True, text=True)
    info = {}
    for line in result.stdout.strip().split("\n"):
        if ":" in line:
            key, val = line.split(":", 1)
            info[key.strip()] = val.strip()
    return info

def get_pdf_text(path):
    """Extract text from a PDF."""
    result = subprocess.run(["pdftotext", "-layout", path, "-"], capture_output=True, text=True)
    return result.stdout

def analyze_ehi_pdf(path):
    """Parse the EHI Export Documentation PDF and extract structured data."""
    text = get_pdf_text(path)
    info = get_pdf_info(path)
    
    # Parse the export categories from the text
    individual_export = {
        "clinical_data": {
            "format": "C-CDA R2.1",
            "standard": "USCDI V1",
            "description": "Clinical data exported in C-CDA R2.1 format compliant with USCDI V1"
        },
        "patient_billing": {
            "format": "CSV",
            "files": ["Claims", "Insurance payment details", "Patient payment details"],
            "description": "Patient billing information in separate CSV files"
        },
        "patient_documents": {
            "format": "Original format (PDF, DOC, HTML, JPG, etc.)",
            "document_types": [
                "Chart Notes (PDF per encounter)",
                "Scanned Documents (PDF)",
                "Imported Faxes (PDF from eFax module)",
                "Documents and Forms generated by software (PDF)",
                "PE Images (image format)",
                "Other imported documents (original format)"
            ],
            "description": "Patient documents exported in original format as individual files"
        },
        "future_appointments": {
            "format": "CSV",
            "description": "Appointments scheduled for future dates"
        },
        "demographics_and_insurance": {
            "format": "CSV",
            "fields_mentioned": [
                "Contact details", "Address", "Emergency contact",
                "Primary Insurance", "Secondary Insurance", "Responsible Party"
            ],
            "description": "Patient demographics, contacts, and insurance information"
        }
    }
    
    population_export = {
        "clinical_data": individual_export["clinical_data"].copy(),
        "patient_billing": individual_export["patient_billing"].copy(),
        "patient_documents_index": {
            "format": "CSV",
            "fields_mentioned": [
                "Document ID", "Patient identification details",
                "Document classification", "Name", "Created date"
            ],
            "description": "Document index CSV; actual documents exported via separate utility program",
            "note": "Nexus provides a document export utility program for offline document export"
        },
        "future_appointments": individual_export["future_appointments"].copy(),
        "demographics_and_insurance": individual_export["demographics_and_insurance"].copy()
    }
    
    return {
        "pdf_metadata": info,
        "pages": int(info.get("Pages", "0")),
        "author": info.get("Author", ""),
        "created": info.get("CreationDate", ""),
        "individual_export": individual_export,
        "population_export": population_export,
        "data_dictionary_present": False,
        "field_level_definitions": False,
        "sample_data_provided": False,
        "schema_files_provided": False,
        "export_mechanism": "UI-driven (Admin users access export module)",
        "bulk_export": True,
        "notes": [
            "No data dictionary or field-level definitions provided",
            "No CSV column headers documented",
            "No sample export files included",
            "No schema or machine-readable format specification",
            "Population export requires contacting Nexus Support for large datasets",
            "Population document export requires separate offline utility program"
        ]
    }

def analyze_costs_pdf(path):
    """Parse the Costs and Considerations PDF."""
    text = get_pdf_text(path)
    info = get_pdf_info(path)
    
    capabilities = [
        {"name": "Base Product (Certified Nexus EHR)", "cost": "Monthly subscription per physician/mid-level provider", "ehi_relevant": False},
        {"name": "Direct Messaging", "cost": "One-time setup + annual subscription", "ehi_relevant": False},
        {"name": "Clinical Decision Support (DynaMed Plus)", "cost": "One-time setup + annual subscription per user", "ehi_relevant": False},
        {"name": "CQM Reports", "cost": "No additional cost", "ehi_relevant": False},
        {"name": "Immunization Registry Submission", "cost": "No additional cost (manual); monthly fee for automated", "ehi_relevant": False},
        {"name": "Syndromic Surveillance", "cost": "No additional cost (manual); monthly fee for automated", "ehi_relevant": False},
        {"name": "Electronic Case Reporting", "cost": "No additional cost (manual); monthly fee for automated", "ehi_relevant": False},
        {"name": "Nexus FHIR API", "cost": "One-time setup + annual subscription", "ehi_relevant": True,
         "note": "FHIR API is separate from EHI export and requires paid subscription"}
    ]
    
    add_on_features = [
        "eFax", "DICOM imaging", "Additional eLabs", "EPCS",
        "Transcription services", "Onsite training", "PDF/Paper form to template conversion",
        "Direct Messaging", "Context aware Knowledge (CDS infobutton)"
    ]
    
    return {
        "pdf_metadata": info,
        "pages": int(info.get("Pages", "0")),
        "capabilities": capabilities,
        "add_on_features": add_on_features,
        "key_finding": "FHIR API requires separate paid subscription; EHI export is a separate mechanism",
        "ehi_export_cost": "Not explicitly listed — appears included in base product"
    }

def main():
    results = {
        "vendor": "Nexus Clinical LLC",
        "product": "Nexus EHR",
        "version": "7.3",
        "chpl_id": "15.04.04.2989.Nexu.07.03.1.221227",
        "analysis_date": "2026-02-15",
        "artifacts_analyzed": []
    }
    
    # Analyze EHI Export Documentation PDF
    ehi_path = os.path.join(DOWNLOADS, "EHI-Export-Documentation.pdf")
    ehi_analysis = analyze_ehi_pdf(ehi_path)
    results["ehi_export_documentation"] = ehi_analysis
    results["artifacts_analyzed"].append({
        "file": "EHI-Export-Documentation.pdf",
        "type": "PDF",
        "size_bytes": os.path.getsize(ehi_path),
        "pages": ehi_analysis["pages"],
        "informativeness": "Primary artifact — describes export format and categories",
        "limitations": "No data dictionary, no field definitions, no sample data"
    })
    
    # Analyze Costs PDF
    costs_path = os.path.join(DOWNLOADS, "Nexus_EHR_Costs_And_Considerations.pdf")
    costs_analysis = analyze_costs_pdf(costs_path)
    results["costs_and_considerations"] = costs_analysis
    results["artifacts_analyzed"].append({
        "file": "Nexus_EHR_Costs_And_Considerations.pdf",
        "type": "PDF",
        "size_bytes": os.path.getsize(costs_path),
        "pages": costs_analysis["pages"],
        "informativeness": "Secondary — confirms FHIR API is separate paid module",
        "limitations": "Standard ONC disclosure, not EHI-specific"
    })
    
    # Screenshot
    screenshot_path = os.path.join(DOWNLOADS, "costs-and-limitations-page-full.png")
    results["artifacts_analyzed"].append({
        "file": "costs-and-limitations-page-full.png",
        "type": "PNG screenshot",
        "size_bytes": os.path.getsize(screenshot_path),
        "informativeness": "Low — visual record of the web page linking to PDFs",
        "limitations": "No additional content beyond what's in the PDFs"
    })
    
    # Summary statistics
    results["summary"] = {
        "total_artifacts": 3,
        "primary_documentation_pages": ehi_analysis["pages"],
        "export_format": "ZIP containing: C-CDA R2.1 + CSV files + raw document files",
        "data_dictionary": False,
        "field_count": "N/A (no data dictionary)",
        "entity_count": "5 export categories (not database entities)",
        "sample_data": False,
        "schema_files": False,
        "csv_files_described": 5,
        "csv_column_headers_documented": 0,
        "export_categories": [
            "Clinical Data (C-CDA R2.1)",
            "Patient Billing (CSV: Claims, Insurance payments, Patient payments)",
            "Patient Documents (original formats)",
            "Future Appointments (CSV)",
            "Patient Demographics and Insurance (CSV)"
        ]
    }
    
    # Write full results
    output_path = os.path.join(OUTPUT_DIR, "full-entity-inventory.json")
    with open(output_path, "w") as f:
        json.dump(results, f, indent=2)
    print(f"Written: {output_path}")
    
    # Print summary
    print("\n=== ANALYSIS SUMMARY ===")
    print(f"Artifacts analyzed: {results['summary']['total_artifacts']}")
    print(f"Primary doc pages: {results['summary']['primary_documentation_pages']}")
    print(f"Export format: {results['summary']['export_format']}")
    print(f"Data dictionary present: {results['summary']['data_dictionary']}")
    print(f"Field-level definitions: No")
    print(f"Sample data: {results['summary']['sample_data']}")
    print(f"Export categories: {len(results['summary']['export_categories'])}")
    for cat in results['summary']['export_categories']:
        print(f"  - {cat}")

if __name__ == "__main__":
    main()
