#!/usr/bin/env python3
"""
Parse the TechCare EHI Export data dictionary from the HTML page and image analysis.
Since the data dictionary is in screenshot images (not machine-readable), the field
data has been manually transcribed from the images into this script.

Source: https://devportal.techcareehr.com/EHIExport
Images: image003.jpg through image020.jpg in downloads/
"""

import json

# Data dictionary transcribed from screenshot images
data_dictionary = {
    "Demographics": {
        "image": "image003.jpg",
        "fields": [
            {"name": "ID", "type": "nvarchar(50)", "description": "Unique patient identifier from OMS/JMS interface, or temporary identifier", "nullable": False, "unique_key": True},
            {"name": "Booking Number", "type": "nvarchar(50)", "description": "Patient booking number from OMS/JMS interface, or temporary identifier generated by TechCare", "nullable": False},
            {"name": "BookingDate", "type": "datetime", "description": "Patient booking date and UTC time", "nullable": False},
            {"name": "CustodyStatus", "type": "nvarchar(50)", "description": "Patient custody status - possible values: ACTIVE or NOT ACTIVE", "nullable": False},
            {"name": "First Name", "type": "nvarchar(50)", "description": "Patient's first name", "nullable": False},
            {"name": "Last Name", "type": "nvarchar(50)", "description": "Patient's last name", "nullable": False},
            {"name": "Date of Birth", "type": "datetime", "description": "Patient's date of birth", "nullable": True},
            {"name": "Gender", "type": "nvarchar(50)", "description": "Sex of patient. M or F or Male or Female", "nullable": True},
            {"name": "HousingLocation", "type": "nvarchar(100)", "description": "Patient's housing location", "nullable": True},
            {"name": "SSN", "type": "nvarchar(50)", "description": "Social Security Number of patient", "nullable": True},
        ]
    },
    "Medications": {
        "image": "image005.jpg",
        "fields": [
            {"name": "Unique Permanent Patient Identifier", "type": "nvarchar(50)", "description": "Unique patient identifier from OMS/JMS interface, or temporary identifier", "nullable": False},
            {"name": "Patient First Name", "type": "nvarchar(50)", "description": "Patient's first name", "nullable": False},
            {"name": "Patient Last Name", "type": "nvarchar(50)", "description": "Patient's last name", "nullable": False},
            {"name": "Patient Date of Birth", "type": "datetime", "description": "Patient's date of birth", "nullable": False},
            {"name": "Description", "type": "varchar(125)", "description": "Full Drug Name from MEDISPAN", "nullable": False},
            {"name": "Instructions", "type": "varchar(500)", "description": "Complete SIG", "nullable": False},
            {"name": "Start Date", "type": "datetime", "description": "Date and UTC time that the order is scheduled to start", "nullable": False},
            {"name": "Stop Date", "type": "datetime", "description": "Date and UTC time that the order is scheduled to expire", "nullable": False},
            {"name": "Patient Date of Birth (2)", "type": "datetime", "description": "Patient's date of birth", "nullable": False},
            {"name": "Medication Order ID", "type": "nvarchar(50)", "description": "Unique identifier for each patient medication order - generated when a medication order is entered - this is TechCare's internal order identifier", "nullable": False, "unique_key": True},
            {"name": "User ID", "type": "nvarchar(100)", "description": "Username from dbo.USERS of the user that created or updated the entry. References: dbo.USERS", "nullable": False},
            {"name": "GPI", "type": "varchar(14)", "description": "Generic Product Identifier", "nullable": False},
            {"name": "Stop Reason", "type": "nvarchar(400)", "description": "Reason entered by the user when discontinuing the order", "nullable": False},
            {"name": "Comments", "type": "nvarchar(250)", "description": "Information that was entered into the 'Additional Information' field on the medication order. Can either be free text, or a selection from the pre-populated drop-down. References: dbo.DRUG_ORDERS_ADDITIONAL_INFO", "nullable": False},
            {"name": "Unique Medication ID", "type": "nvarchar(50)", "description": "Unique identifier for each patient medication order - generated when a medication order is entered - this is TechCare's internal order identifier", "nullable": False},
            {"name": "Route", "type": "nvarchar(100)", "description": "Route that medication is to be administered/taken, e.g., oral, nasal, etc.", "nullable": True},
            {"name": "Order Type", "type": "varchar(500)", "description": "PRN, DOT, KOP when indicated in CompleteSig", "nullable": True},
            {"name": "Quantity", "type": "float", "description": "Medication quantity", "nullable": False},
            {"name": "Refills", "type": "int", "description": "Number of authorized refills. Default: 0", "nullable": False},
            {"name": "Authorizing Provider ID", "type": "nvarchar(50)", "description": "Internal Unique ID assigned to each Prescriber", "nullable": False},
            {"name": "Authorizing Provider NPI", "type": "nvarchar(50)", "description": "Provider's NPI number", "nullable": False},
        ]
    },
    "Allergies": {
        "image": "image007.jpg",
        "fields": [
            {"name": "Unique Permanent Patient Identifier", "type": "nvarchar(50)", "description": "Unique patient identifier from OMS/JMS interface, or temporary identifier. References: dbo.INMATES", "nullable": False},
            {"name": "FirstName", "type": "nvarchar(50)", "description": "Patient's first name", "nullable": False},
            {"name": "LastName", "type": "nvarchar(50)", "description": "Patient's last name", "nullable": False},
            {"name": "Name", "type": "nvarchar(100)", "description": "Allergy name/type. References: dbo.ALLERGIES_ENVIRONMENTAL", "nullable": False},
            {"name": "Onset Date", "type": "datetime", "description": "Date and UTC time that the entry was created or last updated", "nullable": False},
            {"name": "Stop Date", "type": "datetime", "description": "Date and UTC time that the allergy was resolved (if applicable)", "nullable": True},
            {"name": "NDC", "type": "varchar(14)", "description": "Medication NDC if Allergy Class = Drug", "nullable": False},
            {"name": "Allergy Class", "type": "varchar(14)", "description": "Drug, Class [of drugs], or Environmental", "nullable": False},
            {"name": "DateOfBirth", "type": "datetime", "description": "Patient's date of birth", "nullable": False},
            {"name": "GPI", "type": "varchar(14)", "description": "Generic Product Identifier", "nullable": False},
            {"name": "User ID", "type": "nvarchar(100)", "description": "Username from dbo.USERS of the user that created or updated the entry. References: dbo.USERS", "nullable": False},
            {"name": "Stop Reason", "type": "nvarchar(100)", "description": "Information entered by the end user when the allergy is marked as 'resolved'", "nullable": True},
            {"name": "Reaction Description", "type": "nvarchar(150)", "description": "SNOMED concept name", "nullable": False},
        ]
    },
    "Problem List": {
        "image": "image009.jpg",
        "fields": [
            {"name": "InmateID", "type": "nvarchar(50)", "description": "Patient Identifier from OMS/JMS interface, or temporary identifier generated by TechCare. References: dbo.INMATES", "nullable": False},
            {"name": "Firstname", "type": "nvarchar(50)", "description": "Patient's first name", "nullable": False},
            {"name": "Lastname", "type": "nvarchar(50)", "description": "Patient's last name", "nullable": False},
            {"name": "ICD 10 Code", "type": "nvarchar(50)", "description": "Patient diagnosis identifier - ID from dbo.", "nullable": False},
            {"name": "Name", "type": "nvarchar(MAX)", "description": "Patient flag name - NAME from dbo.FLAGS. References: dbo.FLAGS", "nullable": False},
            {"name": "Dateidentified", "type": "datetime", "description": "Date and UTC time that the problem was added", "nullable": False},
            {"name": "Dateresolved", "type": "datetime", "description": "Date and UTC time that the user selected when marking the entry 'resolved'", "nullable": False},
            {"name": "Dateofbirth", "type": "datetime", "description": "Patient's date of birth", "nullable": False},
            {"name": "Resolve", "type": "nvarchar(MAX)", "description": "Text that was entered by the user in the 'Resolve' field when marking the entry 'resolved'", "nullable": False},
            {"name": "Staffidentifier", "type": "nvarchar(50)", "description": "Username from dbo.USERS of the user that created the entry. References: dbo.USERS", "nullable": False},
        ]
    },
    "Flags": {
        "image": "image011.jpg",
        "fields": [
            {"name": "Unique Patient Identifier", "type": "nvarchar(50)", "description": "Unique patient identifier from OMS/JMS interface, or temporary identifier. References: dbo.INMATES", "nullable": False},
            {"name": "Patient First Name", "type": "nvarchar(50)", "description": "Patient's first name", "nullable": False},
            {"name": "Patient Last Name", "type": "nvarchar(50)", "description": "Patient's last name", "nullable": False},
            {"name": "Subject", "type": "nvarchar(500)", "description": "Subject section of the alert - value is pre-populated when an alert is created from an item in a queue or list. This value can also be manually entered and/or updated by end users.", "nullable": False},
            {"name": "Message", "type": "nvarchar(MAX)", "description": "Message body of the alert", "nullable": False},
            {"name": "Alert Date", "type": "datetime", "description": "Date and UTC time that the flag was created", "nullable": False},
            {"name": "Patient Date of Birth", "type": "datetime", "description": "Patient's date of birth", "nullable": False},
            {"name": "Location ID", "type": "nvarchar(100)", "description": "Patient's housing location", "nullable": False},
        ]
    },
    "Appointments": {
        "image": "image012.png",
        "fields": [
            {"name": "InmateId", "type": "nvarchar(50)", "description": "Patient Identifier from OMS/JMS interface, or temporary identifier generated by TechCare. References: dbo.INMATES", "nullable": False},
            {"name": "Firstname", "type": "nvarchar(50)", "description": "Patient's first name", "nullable": False},
            {"name": "Lastname", "type": "nvarchar(50)", "description": "Patient's last name", "nullable": False},
            {"name": "HousingLocation", "type": "nvarchar(100)", "description": "Patient's housing location", "nullable": False},
            {"name": "ScheduledDate", "type": "datetime", "description": "Date that the appointment is scheduled to take place", "nullable": False},
            {"name": "CompletedDate", "type": "datetime", "description": "Date that the appointment was completed", "nullable": False},
            {"name": "TypeId", "type": "int", "description": "Type of appointment - ID from dbo.APPOINTMENT_TYPE. References: dbo.APPOINTMENT_TYPE", "nullable": False},
            {"name": "Name", "type": "nvarchar(100)", "description": "Name of appointment type", "nullable": False},
            {"name": "Status", "type": "int", "description": "Appointment status - ID from dbo.STATUS. References: dbo.STATUS", "nullable": False},
            {"name": "CompletedBy", "type": "nvarchar(100)", "description": "User that completed the appointment - Username from dbo.USERS. References: dbo.USERS", "nullable": False},
            {"name": "Dateofbirth", "type": "datetime", "description": "Patient's date of birth", "nullable": False},
            {"name": "Reason", "type": "nvarchar(2048)", "description": "Reason that the appointment was scheduled", "nullable": False},
            {"name": "Createdby", "type": "nvarchar(100)", "description": "User that created the appointment - Username from dbo.USERS. References: dbo.USERS", "nullable": False},
        ]
    },
    "Diet Orders": {
        "image": "image014.jpg",
        "fields": [
            {"name": "Unique Patient Identifier", "type": "nvarchar(50)", "description": "Patient Identifier from OMS/JMS interface, or temporary identifier generated by TechCare", "nullable": False},
            {"name": "Patient First Name", "type": "nvarchar(50)", "description": "Patient's first name", "nullable": False},
            {"name": "Patient Last Name", "type": "nvarchar(50)", "description": "Patient's last name", "nullable": False},
            {"name": "Patient Date of Birth", "type": "datetime", "description": "Patient's date of birth", "nullable": False},
            {"name": "Order Code", "type": "int", "description": "Numeric Diet Type identifier from dbo.DIET_TYPES", "nullable": False},
            {"name": "Order Description", "type": "nvarchar(200)", "description": "Name of Diet Type from dbo.DIET_TYPES", "nullable": False},
            {"name": "Status", "type": "nvarchar(50)", "description": "Statuses can be changed for diets to ACTIVE/NOT ACTIVE", "nullable": False},
            {"name": "Order Date", "type": "datetime", "description": "Date and UTC time that the entry was created or last updated", "nullable": False},
            {"name": "End Date", "type": "datetime", "description": "Date and UTC time that the diet is scheduled to end", "nullable": False},
            {"name": "User ID", "type": "nvarchar(50)", "description": "Username from dbo.USERS of the user that created or updated the entry", "nullable": False},
            {"name": "Clinical Comments", "type": "nvarchar(MAX)", "description": "Special instructions that were manually entered by the user", "nullable": False},
            {"name": "Cancel Reason", "type": "nvarchar(50)", "description": "Text that was entered by the user in the 'Cancelled' field", "nullable": False},
        ]
    },
    "Lab Orders": {
        "image": "image015.png",
        "fields": [
            {"name": "Unique Patient Identifier", "type": "nvarchar(50)", "description": "Unique patient identifier from OMS/JMS interface, or temporary identifier", "nullable": False},
            {"name": "Patient First Name", "type": "nvarchar(50)", "description": "Patient's first name", "nullable": False},
            {"name": "Patient Last Name", "type": "nvarchar(50)", "description": "Patient's last name", "nullable": False},
            {"name": "Patient Date of Birth", "type": "datetime", "description": "Patient's date of birth", "nullable": False},
            {"name": "Order Code", "type": "nvarchar(50)", "description": "Lab order type - ID from dbo.LAB_TYPES", "nullable": False},
            {"name": "Order Description", "type": "nvarchar(300)", "description": "Name of test", "nullable": False},
            {"name": "Status", "type": "nvarchar(50)", "description": "Name of status", "nullable": False},
            {"name": "Order Date", "type": "datetime", "description": "Date and UTC time that the order was created", "nullable": False},
            {"name": "End Date", "type": "datetime", "description": "Order completion (draw) date", "nullable": False},
            {"name": "User ID", "type": "nvarchar(100)", "description": "Username from dbo.USERS of the user that placed the order", "nullable": False},
            {"name": "Service Provider ID", "type": "nvarchar(100)", "description": "Full name of lab vendor", "nullable": False},
            {"name": "Clinical Comments", "type": "nvarchar(500)", "description": "Corresponds to lab order 'Comment' field", "nullable": False},
            {"name": "Priority", "type": "nvarchar(50)", "description": "Unique identifier for each patient lab order - generated when a lab order is entered", "nullable": False},
            {"name": "Cancel Reason", "type": "nvarchar(50)", "description": "Text that was entered by the user in the 'Cancelled' field", "nullable": False},
        ]
    },
    "Treatment Orders": {
        "image": "image016.png",
        "fields": [
            {"name": "Unique Patient Identifier", "type": "nvarchar(50)", "description": "Unique patient identifier from OMS/JMS interface, or temporary identifier. References: dbo.INMATES", "nullable": False},
            {"name": "Patient First Name", "type": "nvarchar(50)", "description": "Patient's first name", "nullable": False},
            {"name": "Patient Last Name", "type": "nvarchar(50)", "description": "Patient's last name", "nullable": False},
            {"name": "Patient Date of Birth", "type": "datetime", "description": "Patient's date of birth", "nullable": False},
            {"name": "Order Code", "type": "int", "description": "Treatment type identifier - ID from dbo.TREATMENT. References: dbo.TREATMENT_TYPES", "nullable": False},
            {"name": "Order Description", "type": "nvarchar(1000)", "description": "Treatment name entered by the user after 'Free Text' checkbox was checked", "nullable": False},
            {"name": "Status", "type": "nvarchar(50)", "description": "Name of status", "nullable": False},
            {"name": "Order Date", "type": "datetime", "description": "Date and UTC time that the treatment order was created", "nullable": False},
            {"name": "End Date", "type": "datetime", "description": "Date and UTC time that the treatment order is scheduled to expire", "nullable": False},
            {"name": "User ID", "type": "nvarchar(100)", "description": "Username from dbo.USERS", "nullable": False},
            {"name": "Clinical Comments", "type": "nvarchar(300)", "description": "Text information entered into the 'Additional Info.' field while entering the treatment", "nullable": False},
            {"name": "Cancel Reason", "type": "nvarchar(50)", "description": "Text that was entered by the user in the 'Cancelled' field", "nullable": False},
        ]
    },
    "Specialty Consult Orders": {
        "image": "image017.png",
        "fields": [
            {"name": "Unique Patient Identifier", "type": "nvarchar(50)", "description": "Patient Identifier from OMS/JMS interface, or temporary identifier generated by TechCare. References: dbo.INMATES", "nullable": False},
            {"name": "Patient First Name", "type": "nvarchar(50)", "description": "Patient's first name", "nullable": False},
            {"name": "Patient Last Name", "type": "nvarchar(50)", "description": "Patient's last name", "nullable": False},
            {"name": "Patient Date of Birth", "type": "datetime", "description": "Patient's date of birth", "nullable": False},
            {"name": "Order Code", "type": "nvarchar(50)", "description": "Type of off-site (ex. Offsite, Hospitalization, Onsite, Emergency Room, etc.)", "nullable": False},
            {"name": "Order Description", "type": "nvarchar(250)", "description": "Value selected by the user in the 'Specialty' field of the Off-Site/Consult Order - from dbo.OFF_SITE_SPECIALTY_TYPES. References: dbo.OFF_SITE_SPECIALTY_TYPES", "nullable": False},
            {"name": "Status", "type": "nvarchar(250)", "description": "Value that appears for selection in the Off-Site/Consult Order", "nullable": False},
            {"name": "Order Date", "type": "datetime", "description": "Date and UTC time that the record was created", "nullable": False},
            {"name": "End Date", "type": "datetime", "description": "For any status indicating completion or cancellation then Off_Sites.LastUpdateDateTime; else, Empty String (indicating still active)", "nullable": False},
            {"name": "User ID", "type": "nvarchar(50)", "description": "Name of the user that created the record - from dbo.USERS. References: dbo.USERS", "nullable": False},
            {"name": "Clinical Comments", "type": "nvarchar(MAX)", "description": "Information entered by the user in the 'Reason and Timeframe' field of the Off Site/Consult Order", "nullable": False},
            {"name": "Priority", "type": "nvarchar(50)", "description": "Value selected by the user in the 'Priority' field of the Off-Site/Consult Order - from dbo.OFF_SITE_PRIORITY_TYPES. References: dbo.OFF_SITE_PRIORITY_TYPES", "nullable": False},
            {"name": "Cancel Reason", "type": "nvarchar(50)", "description": "Text that was entered by the user in the 'Cancelled' field", "nullable": False},
        ]
    },
    "Admission Orders": {
        "image": "image018.png",
        "fields": [
            {"name": "Unique Patient Identifier", "type": "nvarchar(50)", "description": "Patient Identifier from OMS/JMS interface, or temporary identifier generated by TechCare. References: dbo.INMATES", "nullable": False},
            {"name": "Patient First Name", "type": "nvarchar(50)", "description": "Patient's first name", "nullable": False},
            {"name": "Patient Last Name", "type": "nvarchar(50)", "description": "Patient's last name", "nullable": False},
            {"name": "Patient Date of Birth", "type": "datetime", "description": "Patient's date of birth", "nullable": False},
            {"name": "Order Code", "type": "nvarchar(50)", "description": "Admissions Management Type - ID from dbo.ADMISSION_MANAGEMENT_TYPE. References: dbo.ADMISSION_MANAGEMENT_TYPE", "nullable": False},
            {"name": "Order Description", "type": "nvarchar(50)", "description": "Name of Admissions Management/Group Note type", "nullable": False},
            {"name": "Status", "type": "nvarchar(50)", "description": "Patient status in Admissions Discharge/Group Notes queue - possible values are ACTIVE and NOT ACTIVE", "nullable": False},
            {"name": "Order Date", "type": "datetime", "description": "Date and UTC time stamp that was created when patient was admitted to Admissions Discharge/Group Notes", "nullable": False},
            {"name": "End Date", "type": "datetime", "description": "Date and UTC time stamp that was created when patient was discharged from Admissions Discharge/Group Notes", "nullable": False},
            {"name": "User ID", "type": "nvarchar(100)", "description": "Username from dbo.USERS of the user that created or updated the entry. References: dbo.USERS", "nullable": False},
            {"name": "Clinical Comments", "type": "nvarchar(180)", "description": "Quick Note entries made directly from Admissions Discharge/Group Notes queue", "nullable": False},
            {"name": "Cancel Reason", "type": "nvarchar(50)", "description": "Text that was entered by the user in the 'Cancelled' field", "nullable": False},
        ]
    },
    "Immunizations": {
        "image": "image020.jpg",
        "fields": [
            {"name": "InmateID", "type": "nvarchar(50)", "description": "Patient Identifier from OMS/JMS interface, or temporary identifier generated by TechCare. References: dbo.INMATES", "nullable": False},
            {"name": "FirstName", "type": "nvarchar(50)", "description": "Patient's first name", "nullable": False},
            {"name": "LastName", "type": "nvarchar(50)", "description": "Patient's last name", "nullable": False},
            {"name": "Immunization Group ID", "type": "nvarchar(255)", "description": "Vaccination group name", "nullable": False},
            {"name": "Date Given", "type": "datetime", "description": "Date that vaccine was administered", "nullable": False},
            {"name": "Dateofbirth", "type": "datetime", "description": "Patient's date of birth", "nullable": False},
            {"name": "FullVaccineName", "type": "nvarchar(255)", "description": "Immunization Name", "nullable": False},
            {"name": "Was Given", "type": "varchar(14)", "description": "Yes or No", "nullable": False},
            {"name": "Reason Not Given", "type": "nvarchar(500)", "description": "Information entered into the Reason field of Immunization Entry", "nullable": False},
            {"name": "Historical", "type": "varchar(14)", "description": "Yes or No", "nullable": False},
            {"name": "CVX", "type": "nvarchar(50)", "description": "CVX code from dbo.CVX. References: dbo.CVX", "nullable": False},
            {"name": "AdministeredBy", "type": "nvarchar(MAX)", "description": "Name of individual that administered the vaccine (manually entered)", "nullable": False},
            {"name": "AdministerUnits", "type": "nvarchar(50)", "description": "Units of vaccine administered", "nullable": False},
            {"name": "AdministerUnitsMeasurement", "type": "nvarchar(50)", "description": "Unit of measure - selected by user", "nullable": False},
            {"name": "Route", "type": "nvarchar(MAX)", "description": "Route by which vaccine was administered (intramuscular, intradermal, nasal, etc.)", "nullable": False},
            {"name": "Site", "type": "nvarchar(MAX)", "description": "Vaccine administration site (left arm, right arm, etc.)", "nullable": False},
            {"name": "Manufacturer", "type": "nvarchar(255)", "description": "Vaccine manufacturer name. References: dbo.MVX", "nullable": False},
            {"name": "VaccineLotNumber", "type": "nvarchar(50)", "description": "Lot number of vaccine administered", "nullable": False},
            {"name": "ExpirationDate", "type": "date", "description": "Vaccine expiration date", "nullable": False},
            {"name": "VISPublished", "type": "datetime", "description": "VIS date of publication", "nullable": False},
            {"name": "Administered Comments", "type": "nvarchar(500)", "description": "Information entered into the Clinical Notes field of Immunization Entry", "nullable": False},
            {"name": "Reason Not Given Medical", "type": "nvarchar(MAX)", "description": "Reason that patient refused vaccination", "nullable": False},
            {"name": "Reason Not Given Medical Detail", "type": "nvarchar(MAX)", "description": "Reason that patient refused vaccination", "nullable": False},
            {"name": "VIS Given", "type": "varchar(14)", "description": "Yes or No", "nullable": False},
            {"name": "VIS Given Date", "type": "datetime", "description": "Date that VIS was provided to patient", "nullable": False},
        ]
    },
}

# C-CDA data types (not in CSV, exported via C-CDA document)
ccda_data_types = [
    "Medication Administrations",
    "Vital Signs",
    "Diagnostic Results",
    "Treatment Plans (Plan of Care)",
    "Social History",
    "Assessments",
    "Functional Status",
    "Mental Status",
]

# Compute statistics
total_tables = len(data_dictionary)
total_fields = sum(len(t["fields"]) for t in data_dictionary.values())
fields_with_descriptions = sum(
    1 for t in data_dictionary.values() 
    for f in t["fields"] 
    if f["description"] and len(f["description"]) > 0
)
fields_with_types = sum(
    1 for t in data_dictionary.values() 
    for f in t["fields"] 
    if f["type"] and len(f["type"]) > 0
)

# Foreign key references found
fk_references = set()
for table_name, table in data_dictionary.items():
    for field in table["fields"]:
        desc = field["description"]
        if "References:" in desc or "dbo." in desc:
            # Extract dbo. references
            import re
            refs = re.findall(r'dbo\.(\w+)', desc)
            for ref in refs:
                fk_references.add(ref)

print("=" * 60)
print("TechCare EHI Export - Data Dictionary Analysis")
print("=" * 60)
print()
print(f"CSV Tables:           {total_tables}")
print(f"Total CSV Fields:     {total_fields}")
print(f"Fields w/ Descriptions: {fields_with_descriptions} ({fields_with_descriptions/total_fields*100:.0f}%)")
print(f"Fields w/ Data Types:   {fields_with_types} ({fields_with_types/total_fields*100:.0f}%)")
print(f"C-CDA Data Types:     {len(ccda_data_types)}")
print(f"PDF Attachments:      Yes (images + scanned records)")
print()

print("Per-table breakdown:")
print(f"{'Table':<30} {'Fields':>6} {'Described':>9} {'Typed':>6}")
print("-" * 55)
for name, table in data_dictionary.items():
    n_fields = len(table["fields"])
    n_desc = sum(1 for f in table["fields"] if f["description"])
    n_typed = sum(1 for f in table["fields"] if f["type"])
    print(f"{name:<30} {n_fields:>6} {n_desc:>9} {n_typed:>6}")

print()
print(f"Foreign key references to lookup tables:")
for ref in sorted(fk_references):
    print(f"  - dbo.{ref}")

print()
print(f"C-CDA exported data types:")
for dt in ccda_data_types:
    print(f"  - {dt}")

# Save full inventory as JSON
output = {
    "summary": {
        "csv_tables": total_tables,
        "total_csv_fields": total_fields,
        "fields_with_descriptions": fields_with_descriptions,
        "fields_with_descriptions_pct": round(fields_with_descriptions / total_fields * 100, 1),
        "fields_with_types": fields_with_types,
        "fields_with_types_pct": round(fields_with_types / total_fields * 100, 1),
        "ccda_data_types": len(ccda_data_types),
        "pdf_attachments": True,
    },
    "tables": {
        name: {
            "field_count": len(table["fields"]),
            "source_image": table["image"],
            "fields": table["fields"],
        }
        for name, table in data_dictionary.items()
    },
    "ccda_data_types": ccda_data_types,
    "foreign_key_references": sorted(list(fk_references)),
}

with open("full-entity-inventory.json", "w") as f:
    json.dump(output, f, indent=2)

print()
print("Saved full inventory to full-entity-inventory.json")
